# Generated by Django 4.2.7 on 2025-07-16 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phones', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=5, verbose_name='Телефоны')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, verbose_name='WhatsApp')),
                ('schedule', models.JSONField(blank=True, default=list, verbose_name='Расписание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
