# Generated by Django 4.2.7 on 2025-07-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('client_types', models.JSONField(default=list)),
                ('main_image', models.URLField(blank=True, null=True)),
                ('benefits', models.JSONField(default=list)),
                ('benefits_images', models.JSONField(default=list)),
                ('target', models.CharField(max_length=100)),
                ('products', models.JSONField(default=list)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
