# Generated by Django 4.2.7 on 2025-07-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_types', '0002_alter_servicetype_options_servicetype_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='target',
            field=models.CharField(max_length=200, verbose_name='Цель'),
        ),
    ]
