# Generated by Django 4.2.7 on 2025-08-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_types', '0003_alter_servicetype_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL slug'),
        ),
    ]
