
# docker-compose.yml
version: '3.8'

services:

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=beauty_salon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A beauty_salon_api worker -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=beauty_salon
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A beauty_salon_api beat -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=beauty_salon
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - redis
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=beauty_salon
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  media_volume: