version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=beauty_salon
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A beauty_salon_api worker -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=beauty_salon
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A beauty_salon_api beat -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=beauty_salon
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db
      - redis

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_NAME=beauty_salon
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    restart: on-failure
    depends_on:
      - db
      - redis

  admin_front:  # <-- Новый сервис для админки (Nuxt.js)
    build:
      context: ./h-club_admin_front
      dockerfile: Dockerfile
    ports:
      - "3002:3000"  # Порт из ENV в Dockerfile фронтенда
    volumes:
      - ./h-club_admin_front:/front
      - /front/node_modules  # Изолируем node_modules
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    depends_on:
      - web  # Зависит от бэкенда (если API нужно)
    restart: unless-stopped

volumes:
  postgres_data:
  media_volume:
