# Generated by Django 4.2.7 on 2025-07-16 09:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Изображение')),
                ('job_title', models.CharField(max_length=100, verbose_name='Должность')),
                ('experience', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Опыт работы (лет)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorite_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='favorite_masters', to='products.product', verbose_name='Любимый продукт')),
                ('service_types', models.ManyToManyField(related_name='masters', to='services.servicetype', verbose_name='Типы услуг')),
            ],
            options={
                'verbose_name': 'Мастер',
                'verbose_name_plural': 'Мастера',
            },
        ),
    ]
