# Generated by Django 4.2.7 on 2025-07-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_types', '0002_alter_servicetype_options_servicetype_created_at_and_more'),
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='service_types',
            field=models.ManyToManyField(related_name='masters', to='service_types.servicetype', verbose_name='Типы услуг'),
        ),
    ]
