# Generated by Django 4.2.7 on 2025-07-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_master_service_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='job_title',
            field=models.CharField(max_length=200, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
