# Generated by Django 4.2.7 on 2025-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_types', '0005_alter_servicetype_target'),
        ('masters', '0003_alter_master_job_title_alter_master_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='service_types',
            field=models.ManyToManyField(blank=True, related_name='masters', to='service_types.servicetype', verbose_name='Типы услуг'),
        ),
    ]
