# Generated by Django 4.2.7 on 2025-08-22 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0004_alter_master_service_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Опыт работы (лет)'),
        ),
    ]
