# Generated by Django 4.2.7 on 2025-07-09 12:34

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('client_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('для мужчин', 'Для мужчин'), ('для женщин', 'Для женщин'), ('для детей', 'Для детей')], max_length=20), blank=True, default=list, size=3, verbose_name='Типы клиентов')),
                ('main_image', models.URLField(blank=True, null=True, verbose_name='Основное изображение')),
                ('benefits', models.JSONField(blank=True, default=list, verbose_name='Преимущества')),
                ('benefits_images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=10, verbose_name='Изображения преимуществ')),
                ('target', models.CharField(choices=[('волосы', 'Волосы'), ('маникюр', 'Маникюр'), ('макияж', 'Макияж')], max_length=20, verbose_name='Цель')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='products.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Тип услуги',
                'verbose_name_plural': 'Типы услуг',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена от')),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена до')),
                ('main_images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=2, verbose_name='Основные изображения')),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Продолжительность (часы)')),
                ('steps', models.JSONField(blank=True, default=list, verbose_name='Этапы услуги')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.servicetype', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
