# Generated by Django 4.2.7 on 2025-07-16 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_to', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_images', models.JSONField(default=list)),
                ('duration', models.DecimalField(decimal_places=2, max_digits=4)),
                ('steps', models.JSONField(default=list)),
                ('slug', models.SlugField(unique=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.servicetype')),
            ],
        ),
    ]
