# Generated by Django 4.2.7 on 2025-07-16 10:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_alter_master_service_types'),
        ('service_types', '0002_alter_servicetype_options_servicetype_created_at_and_more'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Продолжительность (часы)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='main_images',
            field=models.JSONField(blank=True, default=list, verbose_name='Основные изображения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_from',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_to',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена до'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='service_types.servicetype', verbose_name='Тип услуги'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL slug'),
        ),
        migrations.AlterField(
            model_name='service',
            name='steps',
            field=models.JSONField(blank=True, default=list, verbose_name='Этапы услуги'),
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
