# Generated by Django 4.2.7 on 2025-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_service_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Продолжительность (часы)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_from',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_to',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена до'),
        ),
    ]
