# Generated by Django 4.2.7 on 2025-07-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_description_alter_service_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='client_types',
            field=models.JSONField(blank=True, default=list, verbose_name='Типы клиентов (массив ID)'),
        ),
        migrations.AddField(
            model_name='service',
            name='target',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(max_length=50, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_from',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена от'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_to',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена до'),
        ),
    ]
