# Generated by Django 4.2.7 on 2025-07-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_client_types_service_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(default='1 час', max_length=50, verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='service',
            name='target',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Цель'),
        ),
    ]
