# Generated by Django 4.2.7 on 2025-07-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_description_alter_service_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='client_types',
            field=models.JSONField(blank=True, default=list, help_text='Например: ["для мужчин", "для женщин", "для детей"]', verbose_name='Типы клиентов (массив строк)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Продолжительность в минутах', null=True, verbose_name='Продолжительность (минуты)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_from',
            field=models.PositiveIntegerField(blank=True, help_text='Цена в рублях', null=True, verbose_name='Цена от (руб.)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price_to',
            field=models.PositiveIntegerField(blank=True, help_text='Цена в рублях', null=True, verbose_name='Цена до (руб.)'),
        ),
    ]
