# Generated by Django 4.2.7 on 2025-07-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_service_client_types_alter_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, help_text='Например: "2 ч. 30 м." или "90 минут"', max_length=100, null=True, verbose_name='Продолжительность'),
        ),
    ]
