# Generated by Django 4.2.7 on 2025-08-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_service_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='URL slug'),
        ),
    ]
