# Generated by Django 4.2.7 on 2025-08-19 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='target',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
