# Generated by Django 4.2.7 on 2025-08-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_service_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='client_types',
            field=models.JSONField(blank=True, default=list, help_text='Например: ["новые", "постоянные"]', verbose_name='Типы клиентов'),
        ),
        migrations.AlterField(
            model_name='service',
            name='target',
            field=models.JSONField(blank=True, default=list, help_text='Например: ["мужчины", "женщины"]', verbose_name='Целевая аудитория'),
        ),
    ]
