# Generated by Django 4.2.7 on 2025-08-19 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_service_target'),
        ('services', '0010_auto_20250819_1336'),
    ]

    operations = [
    ]
