# Generated by Django 4.2.7 on 2025-07-23 13:24

import django.core.validators
from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='cropped_image',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.upload_to_cropped, verbose_name='Обрезанное изображение'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='original_image',
            field=models.ImageField(upload_to=images.models.upload_to_original, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tiff'])], verbose_name='Оригинальное изображение'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.upload_to_processed, verbose_name='Обработанное изображение'),
        ),
    ]
