# Generated by Django 4.2.7 on 2025-07-09 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField(verbose_name='Изображение')),
                ('master', models.JSONField(verbose_name='Мастер')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='services.service', verbose_name='Услуга')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to='services.servicetype', verbose_name='Тип услуги')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
