# Generated by Django 4.2.7 on 2025-08-22 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='service',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='service_type',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='service_types',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Тип услуги'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='services',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Услуга'),
        ),
    ]
